Update to sidekiq v6
CruGlobal/measurements-api pull request #95
Opened 2021-01-27 20:42 UTC by jbirdjavi

2021-02-11 03:48 UTC, soberstadt requested changes

2021-02-11 03:48 UTC, soberstadt commented on config/initializers/sidekiq.rb
>    unique_expiration: 22.days,
I think this should be `lock_timeout`
https://github.com/mhenrixon/sidekiq-unique-jobs#lock_timeout

2021-02-12 02:58 UTC, jbirdjavi commented
This should probably be QAed due to the carrierwave upgrade.

2021-03-17 21:55 UTC, knutsenm approved these changes
Regarding carrierwave: I think we'll be fine. The code uses it in a very basic fashion, and there are tests.

2021-03-18 19:38 UTC, merged